steps:
  # 1️⃣ Ejecutar pruebas unitarias
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install pytest && pytest tests/'

  # 2️⃣ Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/devops-engineer-technical-test/my-repo/my-app:latest'
      - '.'

  # 3️⃣ Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/devops-engineer-technical-test/my-repo/my-app:latest'

  # 4️⃣ Desplegar en GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
  - 'us-central1-docker.pkg.dev/devops-engineer-technical-test/my-repo/my-app:latest'